export const states = {
  LOBBY: 'LOBBY',
  END: 'END',
  PRESENT_WORD_INPUT_EXPLANATION: 'PRESENT_WORD_INPUT_EXPLANATION',
  SELECT_EXPLANATION: 'SELECT_EXPLANATION',
  PRESENT_ANSWER: 'PRESENT_ANSWER',
  PRESENT_SCORE: 'PRESENT_SCORE',
};

export const colors = ['peach', 'grass', 'beach', 'ocean'];
